### PR TITLE
Add support for Azure Function v4

### PR DESCRIPTION
**Pull request by barddoo**
Solves https://github.com/apollo-server-integrations/apollo-server-integration-azure-functions/issues/41

That's how the api looks like:
```ts
import { ApolloServer } from '@apollo/server';
import { v4 } from '@as-integrations/azure-functions';

// The GraphQL schema
const typeDefs = `#graphql
  type Query {
    hello: String
  }
`;

// A map of functions which return data for the schema.
const resolvers = {
  Query: {
    hello: () => 'world',
  },
};

// Set up Apollo Server
const server = new ApolloServer({
  typeDefs,
  resolvers,
});

app.http('graphql', {
  handler: v4.startServerAndCreateHandler(server),
});
```

### CODE REVIEW

**Comment by cqhung1412** [comment]
@aaronpowell please review this and merge soon

**Comment by gidich** [comment]
@aaronpowell any plans on when this may get merged in? - Azure Function Programming Model v4 is now GA

**Comment by heruwala** [comment]
We are currently in the process of upgrading to utilize Azure Function Programming Model v4. This pull request (PR) is crucial for us to proceed with the upgrade. Kindly merge at your earliest convenience. Thank you.

**Comment by Mingyang-Li** [comment]
Hey team, looking forward to seeing this PR getting merged 🙏🙏

**Pull request merged**
